services:
  php-cli:
    image: ghcr.io/sitepilot/php-cli:8.3
    profiles:
      - donotstart
    build:
      context: ./src
      target: cli

  php-fpm:
    image: ghcr.io/sitepilot/php-fpm:8.3
    build:
      context: ./src
      target: fpm

  php-nginx:
    image: ghcr.io/sitepilot/php-nginx:8.3
    build:
      context: ./src
      target: nginx
    ports:
      - 8080:80
      - 8443:443

  php-ols:
    image: ghcr.io/sitepilot/php-ols:8.3
    build:
      context: ./src
      target: ols
    ports:
      - 9080:80
      - 9443:443
      - 9070:7080
