services:
  php-cli:
    image: ghcr.io/sitepilot/php-cli:8.1
    profiles:
      - donotstart
    build:
      context: ./src
      target: cli

  php-fpm:
    image: ghcr.io/sitepilot/php-fpm:8.1
    build:
      context: ./src
      target: fpm

  php-nginx:
    image: ghcr.io/sitepilot/php-nginx:8.1
    build:
      context: ./src
      target: nginx
    ports:
      - 8080:80
      - 8443:443

  php-ssh:
    image: ghcr.io/sitepilot/php-ssh:8.1
    build:
      context: ./src
      target: ssh
    ports:
      - 8022:22
    environment:
      RUNTIME_UID: 1001
      RUNTIME_GID: 1001
      RUNTIME_USER: test-user
      RUNTIME_GROUP: test-group
      RUNTIME_PASSWORD: supersecret

  php-ols:
    image: ghcr.io/sitepilot/php-ols:8.1
    build:
      context: ./src
      target: ols
    ports:
      - 9080:80
      - 9443:443
