#!/usr/bin/env bash

# Start php-fpm
php-fpm -F &
PHP_FPM_PID=$!

# Start nginx
nginx -g 'daemon off;' &
NGINX_PID=$!

# Stop services
trap 'echo SIGINT; kill -s SIGINT $PHP_FPM_PID $NGINX_PID' SIGINT
trap 'echo SIGTERM; kill -s SIGTERM $PHP_FPM_PID $NGINX_PID' SIGTERM

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?
