name: build

on:
  push:
    branches:
      - 1.x
    paths:
      - 'src/**'
  schedule:
    - cron: '25 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from branch name
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "VERSION=v${BRANCH/.x/}" >> $GITHUB_ENV

      - php-cli:
          uses: ./.github/workflows/build-and-test.yml
          with:
            target: cli
            version: ${{ matrix.php }}
            tests: |
              docker run ghcr.io/sitepilot/php-cli:build php -v
              docker run ghcr.io/sitepilot/php-cli:build wp --version
              docker run ghcr.io/sitepilot/php-cli:build composer --version

      - php-fpm:
          uses: ./.github/workflows/build-and-test.yml
          with:
            target: fpm
            version: ${{ matrix.php }}
            tests: |
              docker run ghcr.io/sitepilot/php-fpm:build php-fpm --version

      - php-nginx:
          uses: ./.github/workflows/build-and-test.yml
          with:
            target: nginx
            version: ${{ matrix.php }}
            tests: |
              docker run ghcr.io/sitepilot/php-nginx:build nginx -v
              docker run ghcr.io/sitepilot/php-nginx:build nginx -t

      - php-ssh:
          uses: ./.github/workflows/build-and-test.yml
          with:
            target: ssh
            version: ${{ matrix.php }}
            tests: |
              docker run ghcr.io/sitepilot/php-ssh:build ssh -V
