name: build

on:
  push:
    branches:
      - 1.x
    paths:
      - 'src/**'
  schedule:
    - cron: '25 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
        platform: [ 'linux/amd64', 'linux/arm64' ]
        include:
          - platform: 'linux/amd64'
            runner: 'ubuntu-22.04'
          - platform: 'linux/arm64'
            runner: 'self-hosted'

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from branch name
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "VERSION=v${BRANCH/.x/}" >> $GITHUB_ENV

      - name: Build php-cli image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/sitepilot/php-cli:${{ matrix.php }}
            ghcr.io/sitepilot/php-cli:${{ env.VERSION }}-${{ matrix.php }}
          platforms: ${{ matrix.platform }}
          target: cli
          provenance: false
          cache-from: type=gha,scope=cli
          cache-to: type=gha,mode=max,scope=cli
          build-args: |
            PHP_VERSION=${{ matrix.php }}

      - name: Build php-fpm image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/sitepilot/php-fpm:${{ matrix.php }}
            ghcr.io/sitepilot/php-fpm:${{ env.VERSION }}-${{ matrix.php }}
          platforms: ${{ matrix.platform }}
          target: fpm
          provenance: false
          cache-from: type=gha,scope=fpm
          cache-to: type=gha,mode=max,scope=fpm
          build-args: |
            PHP_VERSION=${{ matrix.php }}

      - name: Build php-nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/sitepilot/php-nginx:${{ matrix.php }}
            ghcr.io/sitepilot/php-nginx:${{ env.VERSION }}-${{ matrix.php }}
          platforms: ${{ matrix.platform }}
          target: nginx
          provenance: false
          cache-from: type=gha,scope=nginx
          cache-to: type=gha,mode=max,scope=nginx
          build-args: |
            PHP_VERSION=${{ matrix.php }}

      - name: Build php-ssh image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/sitepilot/php-ssh:${{ matrix.php }}
            ghcr.io/sitepilot/php-ssh:${{ env.VERSION }}-${{ matrix.php }}
          platforms: ${{ matrix.platform }}
          target: ssh
          provenance: false
          cache-from: type=gha,scope=ssh
          cache-to: type=gha,mode=max,scope=ssh
          build-args: |
            PHP_VERSION=${{ matrix.php }}
