name: build

on:
  push:
    branches:
      - 1.x
    paths:
      - 'src/**'
  schedule:
    - cron: '25 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  runtime:
    uses: ./.github/workflows/build-and-test.yml
    with:
      image: runtime
      target: runtime
      tests: |
        docker run ghcr.io/sitepilot/runtime:build id
        docker run --user=root -e RUNTIME_PASSWORD=supersecret ghcr.io/sitepilot/runtime:build id app
        docker run --user=root -e RUNTIME_UID=1001 -e RUNTIME_GID=1001 ghcr.io/sitepilot/runtime:build id app
        docker run --user=root -e RUNTIME_USER=test-user -e RUNTIME_GROUP=test-group ghcr.io/sitepilot/runtime:build id test-user
    secrets: inherit

  php-cli:
    uses: ./.github/workflows/build-and-test-php.yml
    with:
      target: cli
      tests: |
        docker run ghcr.io/sitepilot/php-cli:build php -v
        docker run ghcr.io/sitepilot/php-cli:build wp --version
        docker run ghcr.io/sitepilot/php-cli:build composer --version
    secrets: inherit

  php-fpm:
    uses: ./.github/workflows/build-and-test-php.yml
    with:
      target: fpm
      tests: |
        docker run ghcr.io/sitepilot/php-fpm:build php-fpm --version
    secrets: inherit

  php-nginx:
    uses: ./.github/workflows/build-and-test-php.yml
    with:
      target: nginx
      tests: |
        docker run ghcr.io/sitepilot/php-nginx:build nginx -v
        docker run ghcr.io/sitepilot/php-nginx:build nginx -t
    secrets: inherit

  php-ols:
    uses: ./.github/workflows/build-and-test-php.yml
    with:
      target: ols
      tests: |
        docker run ghcr.io/sitepilot/php-ols:build php -v
        docker run ghcr.io/sitepilot/php-ols:build wp --version
        docker run ghcr.io/sitepilot/php-ols:build composer --version
        docker run ghcr.io/sitepilot/php-ols:build /usr/local/lsws/bin/litespeed -v
    secrets: inherit
