name: build

on:
  push:
    branches:
      - '1.x'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '1.x'

jobs:
  php-cli:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: cli
      tests: |
        docker run ghcr.io/sitepilot/php-cli:build php -v
        docker run ghcr.io/sitepilot/php-cli:build wp --version
        docker run ghcr.io/sitepilot/php-cli:build composer --version
    secrets: inherit

  php-fpm:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: fpm
      tests: |
        docker run ghcr.io/sitepilot/php-fpm:build php-fpm --version
    secrets: inherit

  php-nginx:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: nginx
      tests: |
        docker run ghcr.io/sitepilot/php-nginx:build nginx -v
        docker run ghcr.io/sitepilot/php-nginx:build nginx -t
    secrets: inherit

  php-ols:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: ols
      tests: |
        docker run ghcr.io/sitepilot/php-ols:build /usr/local/lsws/bin/litespeed -v
    secrets: inherit

  php-ssh:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: ssh
    secrets: inherit
