on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      version:
        required: true
        type: string
      tests:
        required: false
        type: string
        default: ''

jobs:
  - name: Build php-${{ inputs.target }} image
    uses: docker/build-push-action@v5
    with:
      context: ./src
      pull: true
      tags: ghcr.io/sitepilot/php-${{ inputs.target }}:build
      target: ${{ inputs.target }}
      cache-from: type=gha,scope=php-${{ inputs.target }}-${{ env.VERSION }}-${{ inputs.version }}
      build-args: |
        PHP_VERSION=${{ inputs.version }}

  - name: Test php-${{ inputs.target }} image
    run: ${{ inputs.tests }}
    when: ${{ inputs.tests != '' }}

  - name: Push php-${{ inputs.target }} image
    uses: docker/build-push-action@v5
    with:
      context: ./src
      push: ${{ github.event_name != 'pull_request' }}
      tags: |
        ghcr.io/sitepilot/php-${{ inputs.target }}:${{ inputs.version }}
        ghcr.io/sitepilot/php-${{ inputs.target }}:${{ env.VERSION }}-${{ inputs.version }}
      platforms: linux/amd64, linux/arm64
      target: ${{ inputs.target }}
      provenance: false
      cache-to: type=gha,mode=max,scope=php-${{ inputs.target }}-${{ env.VERSION }}-${{ inputs.version }}
      build-args: |
        PHP_VERSION=${{ inputs.version }}
