name: build

on:
  push:
    branches:
      - 1.x
    paths:
      - 'src/**'
  schedule:
    - cron: '25 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  php-cli:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: cli
      tests: |
        docker run ghcr.io/sitepilot/php-cli:build php -v
        docker run ghcr.io/sitepilot/php-cli:build wp --version
        docker run ghcr.io/sitepilot/php-cli:build composer --version
    secrets: inherit

  php-fpm:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: fpm
      tests: |
        docker run ghcr.io/sitepilot/php-fpm:build php-fpm --version
    secrets: inherit

  php-nginx:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: nginx
      tests: |
        docker run ghcr.io/sitepilot/php-nginx:build nginx -v
        docker run ghcr.io/sitepilot/php-nginx:build nginx -t
    secrets: inherit

  php-ssh:
    uses: ./.github/workflows/build-and-test-job.yml
    with:
      target: ssh
      tests: |
        docker run ghcr.io/sitepilot/php-ssh:build ssh -V
    secrets: inherit
